### ISSUE TITLE
✅ FEATURE : 엔티티 구성

### ISSUE THREAD

**Issue by Jin409** [SopkathonTeam3/server#2]
## ✅ 구현 내용
- 엔티티 구성

## 📝 todo
- [x] post 엔티티 생성
- [x] user 엔티티 생성
- [x] room 엔티티 생성
- [x] background image 엔티티 생성
