### ISSUE TITLE
✅ FEATURE : post 조회 페이지 기능 구현

### ISSUE THREAD

**Issue by Jin409** [SopkathonTeam3/server#5]
## ✅ 구현 내용
- post 조회 페이지에서 사용되는 기능들을 구현

## 📝 todo
- [x] 메모 전체 조회 기능
- [x] room 정보 조회 기능
- [x] 프로필 조회 기능
